### ISSUE TITLE
[SN-CommunitySite]Tutorial page revamp

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#174]
- [ ] Tutorial homepage with the three separate way of creating an app (React, Aurelia, MVC)
- [ ] Old non-related tutorials should be archived somehow
- [ ] Tutorial subpages should have a 'table-of-contents' menu to switch between tutorials and demonstrate the sequence
- [ ] All the tutorials should have a 'pager' to go back and forth between tutorials

[https://www.meteor.com/tutorials](https://www.meteor.com/tutorials)
