### ISSUE TITLE
Blog posts

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet.github.io#34]
- [x] SNTeam Q1 goals, metrics and achievements
- [ ] ~~Q2 goals - where are we going?~~
- [x] We moved to Github
- [x] Sensenet 5% - The FreeFriday project

## snteam 
- [x] Why NuGet? - @tusmester maybe?
- [x] Why JWT?
- [x] [Frontend-releases](https://github.com/SenseNet/sensenet.github.io/issues/120) 
- [x] [Starting out with Reactjs](https://github.com/SenseNet/sensenet.github.io/issues/112)
- [x] [SN7 stable version is out](https://github.com/SenseNet/sensenet.github.io/issues/125)
- [x] [OAuth in sensenet](https://github.com/SenseNet/sensenet.github.io/issues/124)
- [ ] [How we document things with typedoc](https://github.com/SenseNet/sensenet.github.io/issues/116) :ok_hand:
- [x] [Starting out with Aureliajs](https://github.com/SenseNet/sensenet.github.io/issues/131)
- [x] [How to create a new MVC app with sensenet](https://github.com/SenseNet/sensenet.github.io/issues/132)
- [ ] [DMS MVP](https://github.com/SenseNet/sensenet.github.io/issues/121) 
- [x] [first SN7 patch, how to install it?](https://github.com/SenseNet/sensenet.github.io/issues/141)
- [ ] Google, Facebook, etc auth on the client-side
- [ ] Roadmap 2018
- [x] [2017 Q4 results](https://github.com/SenseNet/sensenet.github.io/pull/139) 
- [x] [2018 Q1 goals](https://github.com/SenseNet/sensenet.github.io/pull/140) 
- [x] [Switch to scoped npm packages](https://github.com/SenseNet/sensenet.github.io/issues/149) 
- [x] [Refactoring sn-redux](https://github.com/SenseNet/sensenet.github.io/pull/152) :ok_hand:
- [x] [A complex patch](https://github.com/SenseNet/sensenet.github.io/pull/164) :ok_hand:
- [x] [2018 Q2 goals](https://github.com/SenseNet/sensenet.github.io/pull/143) :ok_hand:
- [ ] 2018 Q3 goals
- [ ] 2018 Q4 goals
- [x] [2018 Q1 results](https://github.com/SenseNet/sensenet.github.io/pull/178) :ok_hand:
- [ ] 2018 Q2 results
- [ ] 2018 Q3 results
- [ ] 2018 Q4 results
- [ ] New sn search API
- [ ] Something Azure related
- [ ] CTD improvements
- [ ] Something about how we measure sandboxes and DMS MPV
- [ ] SN7 in the cloud
- [ ] [Upgrade your sensenet 6.5 to 7+](https://github.com/SenseNet/sensenet.github.io/issues/187)
- [ ] How to GDPRize your DMS with sensenet
- [ ] Refactoring the ContentLists in SN7
- [ ] Something about how we in snteam work together
- [ ] Inhouse trainings and workshops
- [ ] Making of the SN7 training material
- [ ] ContentType vs Schema on clientside
- [ ] Localization improvements
- [ ] [How to protect your document in your content repository?](https://github.com/SenseNet/sensenet/issues/104)
- [ ] How we work on GitHub: the ZenHub board
- [ ] SN Installer

**Comment by balazskeszei** [comment]
Write an introduction to "sensenet ECM 7.0 components" description in the blog section.
Write an overview about CTD, why is it good? How do clients (should) use it?
