### ISSUE TITLE
Q1 'kontent kedd' materials (docs, posts, imgz, website content...)

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#416]
#### API DOCS
_The new docs will be placed temporarily [here](https://github.com/SenseNet/sensenet.github.io/content/docs/api). The articles have a separate md file and the examples should be placed this way [/content/docs/api/examples/$articlename/$examplename/$language.md](https://github.com/SenseNet/sensenet.github.io/content/docs/api/examples) (e.g. load a content by its Id js example should be created as [https://github.com/SenseNet/sensenet.github.io/content/docs/api/examples/entry/byId/js.md](https://github.com/SenseNet/sensenet.github.io/content/docs/api/examples/entry/byId/js.md))
All examples should have now four separate 'language' versions (REST, .NET, js and reactjs)_

_If you want to mark where example code should be placed add a comment:_ 
```[comment]: # (Example here - REST, .NET, JavaScript, Reactjs)```

##### BASIC CONCEPTS
- [x] Introduction
- [x] Entry
   - [x] by Id
   - [x] by Path
   - [x] addressing a property
   - [x] addressing a property value
- [x] Collection
   - [x] children
   - [x] count
   - [x] inlinecount
- [x] Select and expand
- [x] Ordering and paging
- [x] Searching and filtering
- [x] Count
- [x] Metadata
- [x] System content
- [x] Lifespan
- [x] Actions
- [x] Schema
##### QUERYING
- [x] How to Query the API
- [x] Query by Id or Path
- [x] Query by a Field
- [x] Query by Type
- [x] Query by Date
- [x] Query by Content relationship
- [x] Fulltext Search
- [x] Multiple predicates
- [x] Ordering
- [x] Paging
- [x] Count
- [x] Query system content
- [x] Template parameters
##### CONTENT MANAGEMENT
- [x] Introduction
- [x] Create
- [x] Update (patch/put)
- [x] Delete
- [x] Upload
- [x] Copy/move
- [x] Allowedchildtypes (checkallowedchildtypes, addtypes, removetypes, etc)
- [x] Trash (restore, delete)
##### COLLABORATION
- [x] Versioning (checkin,checkout,undocheckout,forceundo)
- [x] Approval (approve, reject, publish)
- [x] Saved queries
##### USERS AND GROUPS
- [x] Login
- [x] Logout
- [x] Registration
- [x] Change password
- [x] Forgotten password
- [x] Add/remove members from a group
##### PERMISSIONS
- [x] Permissions management (getpermissions/setpermission/haspermission)
- [x] Permission queries
##### PREVIEW
- [x] preview actions
#### SHARING
- [x ] sharing actions

#### CONCEPTS
_The new docs will be placed temporarily [here](https://github.com/SenseNet/sensenet.github.io/content/docs/concepts)._
- [x] Content models/schema
- [x] Content tree
- [x] Content relations (tree, reference, allowed child types)
- [x] Content management/Actions
- [x] Versioning and approval
- [x] User management
- [x] Role based permissions
- [x] Document level permissions 
- [x] Search features (full text, stop words, boosting, stemming, search in uploaded docs)
- [x] Client side forms
#### TUTORIALS
_The new tutorials will be placed temporarily [here](https://github.com/SenseNet/sensenet.github.io/content/docs/tutorials)._
- [ ] Client side forms
- [ ] Authentication from a js app
- [ ] Authentication from an mvc app
- [ ] Using the sharing API -> example app
- [ ] How to add a new feature
#### INTEGRATIONS
- [ ] React controls
- [ ] * Gatsby source plugin
- [ ] * Gatsby starter kit
- [ ] Integrate third party validator
- [ ] OCR
- [ ] Digital signature
### BLOGPOSTS
_The new blog posts should remain in the current [_draft folder](https://github.com/SenseNet/sensenet.github.io/_draft) as before._
- [ ] q1 goals
- [x] frontend performance improvements
- [ ] new permission editor
### IMGZ
_Images should be uploaded in a new separate folder [here](https://github.com/SenseNet/sensenet.github.io/content/img)_
#### Illustrations for the concept/feature docs
- [ ] Content repository
- [ ] Permission system
- [x] Versioning and approval
- [x] Collaboration (office online editing, etc.)
